---
global:
  env: preview
  helmDefault: true
  valuesFile: values.yaml
  destinations:
    - name: platform-preview
  source:
    repoURL: https://github.com/bookmanj/argocd-app-of-apps.git
    targetRevision: HEAD

argocdApplications:
  argo-rollouts:
    namespace: argo-rollouts
    project: addons

  kube-prometheus-stack:
    namespace: monitoring
    project: addons
