{{- range $app, $val := .Values.argocdApplications -}}
{{ if not .disable }}
{{ if .namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
{{- end }}
{{- end }}
{{- end }}