{{- range $app, $val := .Values.argocdApplications -}}
{{ if not .disable }}
{{ if .project }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .project }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
{{- end }}
{{- end }}
{{- end }}
